services:
  tiny-note:
    build: ./web
    restart: unless-stopped
    init: true
    networks:
      - isolated
  tiny-note-nginx:
    build:
      context: ./nginx
      dockerfile_inline: |
        FROM nginx:1.27.5
        COPY ./nginx.conf /etc/nginx/conf.d/default.conf
    ports:
      - ${PORT:-3000}:3000
    networks:
      - default
      - isolated

networks:
  isolated:
    internal: true
