services:
  redirector:
    build: ./web
    restart: unless-stopped
    init: true
    ports:
      - ${PORT_WEB:-3000}:3000
  redirector-bot:
    build: ./bot
    restart: unless-stopped
    init: true
    ports:
      - ${PORT_BOT:-1337}:1337
    environment:
      - FLAG=Alpaca{An_0pen_redirec7_is_definite1y_a_vuln3rability}
