services:
  web:
    build: ./web
    restart: unless-stopped
    ports:
      - 3000:3000
    init: true
  bot:
    build: ./bot
    restart: unless-stopped
    init: true
    ports:
      - 1337:1337
    environment:
      - FLAG=ASIS{REDACTED}
