services:
  web:
    build: ./web
    restart: unless-stopped
    init: true
    ports:
      - ${PORT_WEB:-3000}:3000
  bot:
    build: ./bot
    restart: unless-stopped
    init: true
    ports:
      - ${PORT_BOT:-1337}:1337
    environment:
      - FLAG=Alpaca{REDACTED}
