services:
  disconnection:
    build: ./web
    restart: unless-stopped
    init: true
    ports:
      - ${PORT_WEB:-3000}:3000
  disconnection-bot:
    build: ./bot
    restart: unless-stopped
    init: true
    ports:
      - ${PORT_BOT:-1337}:1337
    environment:
      - FLAG=Alpaca{browser_behavior_is_to0o0o0o0o0o0o0_complicated}
