name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: mv README.md README.md.bak
      - run: deno task build
      - run: diff README.md README.md.bak
